title: Tuan's dev blog
author: Tuan (s76)
subtitle: Tuan's dev blog

url: "https://s76.github.io"
baseurl: ""

footer_url: "https://github.com/pro-panda/parchment"
footer_text: "Original theme 'Parchment' by pro-panda, modified by me"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
